name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # This cron syntax schedules the workflow to run nightly at midnight UTC

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build/ # Update this to the actual path of your artifact   

  # Test Job
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo this is test job!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  # Deploy Job
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: review # Define environment for deployment (this can be customized)

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Review Environment
        run: |
          echo Deploying to review environment...
          # Replace the following with your actual deployment command
          # For example, using AWS CLI, SSH, or any deployment scripts.
          # aws deploy ... 
          
      - name: Confirm deployment to Review Environment
        run: echo "Deployment to Review Environment Successful!"

